### ISSUE TITLE
读论文感到的困惑

### ISSUE THREAD

**Issue by ckxkexing** [roadfar/MotivationsInSO#1]
作者你好，
在论文第11页左下角，你说intrinsic motivation中的help other(对应fig2中的INT2)和effort正相关。
<img width="602" alt="image" src="https://user-images.githubusercontent.com/40681177/176185030-23ebe757-d010-4be1-a5ae-b943700143a0.png">
但是从表6来看
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/40681177/176184203-dd4d39be-8a9a-4d44-b64f-77eefbe007f4.png">
INT2这一行没有红星，也只有最后一列是稍微大于0的值。

另外，
对于偏最小二乘法，是否只需要看表中带红星的数据(p<0.05)，其余数据不一定有说服性？

期待作者的解答，谢谢！

**Comment by roadfar** [comment]
@ckxkexing 你好，感谢对本论文的关注及重要反馈！
1）我们仔细检查了下，这里确实是在将数据录入Latex代码时粗心弄错了INT1、INT2、INT3的行序，因为模型输出数据的行序与Latex表格呈现的行序不一致，Table 6应该做如下调整：
![image](https://user-images.githubusercontent.com/11403509/176897971-3c6339eb-8b08-433b-8e08-da6f4d2b20f6.png)
正确的顺序应该是：
![image](https://user-images.githubusercontent.com/11403509/176898022-317a01ef-b2bb-4102-a36a-cc305a3654b9.png)

包括在Table 7中也有类似的问题，应该做如下调整：
![image](https://user-images.githubusercontent.com/11403509/176897620-6dc1a969-4d31-4f1d-9e62-9cefc36b4f00.png)
正确的顺序应该是：
![image](https://user-images.githubusercontent.com/11403509/176897677-df0e197f-67ba-4583-bd76-e3611e1bd6a2.png)

**这篇论文目前还处于Early access 阶段，我们已发邮件给编辑希望能够更新论文，等回复中，有什么结果也会在这个issue下发布，希望能好运：）**

2）根据RQ，这里主要关注开发者的动机、需要满足度以及个体特征中哪些自变量会对贡献投入和质量有显著影响，因此主要关注影响关系显著的那些变量（p value<0.05）

**Comment by roadfar** [comment]
期刊编辑已回复，允许更新论文pdf，应该过两天就可以下载到更新后的版本~
感谢@ckxkexing 的反馈和编辑的支持！
